name: Node CI
on:
  pull_request:
    branches:
    - PR_DEPLOY_DEV

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get PR Info 
      env:
        PR_DEPLOY_FRIENDLY_SUFFIX: myra
      run: |
        grep findThisVar $GITHUB_EVENT_PATH 
